version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
        - mongo
    depends_on:
        - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - "27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet